# Generated by Django 5.0.3 on 2024-03-15 12:57

import django.db.models.expressions
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='excerpt',
            field=models.GeneratedField(db_persist=False, expression=django.db.models.functions.text.Trim(django.db.models.functions.text.Substr('description', django.db.models.expressions.CombinedExpression(django.db.models.functions.text.StrIndex('description', models.Value('#')), '+', models.Value(1)), django.db.models.functions.text.StrIndex('description', models.Value('\n')))), output_field=models.CharField(max_length=250)),
        ),
    ]
